//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod invite;
pub mod password;
pub mod record;
pub mod record_a;
pub mod record_aaaa;
pub mod record_cname;
pub mod record_mx;
pub mod record_ns;
pub mod record_txt;
pub mod user;
pub mod zone;
