//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (table_name = "zone")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , pub created : TimeDateTimeWithTimeZone , pub admin : String , pub name : String , pub refresh : i32 , pub retry : i32 , pub expire : i32 , pub minimum : i32 , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }